name: "Nuvio Remote Files"
slug: "nuvio_remote_files"
version: "1.3.0"
description: "Server Stremio locale per HAOS: indicizza e serve i tuoi film e serie da dischi USB."
url: "https://github.com/S1mone01/Nuvio-remote-files-ha-addon"
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
map:
  - media:rw
  - data:rw
init: false
ingress: true
ingress_port: 8080
panel_icon: "mdi:movie-play"
panel_title: "Stremio Remote"
ports:
  8080/tcp: 8080
options:
  port: 8080
  tmdb_api_key: ""
  admin_scan_token: "secret_token_123"
  movies_dir_name: "movies"
  series_dir_name: "series"
  downloads_dir_name: "downloads"
  trusted_networks: "192.168.0.0/16 10.0.0.0/8 172.16.0.0/12"
  media_disk_name: "EXTERNAL_USB"
  media_subpath: ""
  media_base_url: ""
schema:
  port: port
  tmdb_api_key: str
  admin_scan_token: str
  movies_dir_name: str
  series_dir_name: str
  downloads_dir_name: str
  trusted_networks: str
  media_disk_name: str
  media_subpath: str?
  media_base_url: str?
